Monitoring Agent
jarvisgroup/jarvis_data_eng_zongpeng pull request #6
Opened 2019-11-28 17:28 UTC by ZongpengYang

https://www.notion.so/Monitoring-Agent-dda775b86873446e9e01acc97592c121

2019-12-01 21:49 UTC, ghost requested changes

2019-12-01 21:49 UTC, jarvisgroup commented on linux_sql/scripts/host_info.sh
> +psql -h $1 -U $4 -w $3 -p $2 -c \
please follow the coding style

2019-12-01 21:49 UTC, jarvisgroup commented on linux_sql/scripts/host_info.sh
> +# collecting infomation
no args check

2019-12-02 13:27 UTC, Cathy-Xin approved these changes

2019-12-02 17:49 UTC, merged